#!/bin/bash
#
# Update a superproject when a commit is made to a submodule.
# Intended for .git/**modules/{THE_SUBMODULE}/hooks/post-commit
# where the double-star indicates variadic path elements.
#
# Depends on Git >= 2.13.

# Clean the Git environment before crossing repository boundaries.
# From https://stackoverflow.com/questions/36196548/cannot-trigger-post-commit-git-hook-on-git-submodule
while read variable; do
    unset $variable
done < <(env | grep "^GIT_" | sed 's/=.*//g')

COMMIT_MSG="chore: update submodules"
GIT="git"
SUPERPROJECT_WORKING_TREE=$(git rev-parse --show-superproject-working-tree)
echo "📣 Committing to $SUPERPROJECT_WORKING_TREE."
cd $SUPERPROJECT_WORKING_TREE || exit
$GIT reset .
$GIT add keincraft
$GIT add keincraft-test
$GIT commit -m "$COMMIT_MSG"